version: '3'

volumes:
  local_mysql_data: {}

services:
  flask: &flask
    build:
      context: .
      dockerfile: ./compose/dev/flask/Dockerfile
    image: kvm_flask
    depends_on:
      - mysql
    volumes:
      - .:/app
    env_file:
      - ./.environments/dev/flask/.flask
      - ./.environments/dev/mysql/.mysql
    ports:
      - 5000:5001
    command: /start

  mysql:
    image: mysql/mysql-server:5.7.21
    volumes:
      - local_mysql_data:/var/lib/mysql
    env_file:
      - ./.environments/dev/mysql/.mysql

